version: "3.9"
services:
  web:
    build: .
    ports:
      - "12000:9000"
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_RUN_RELOAD: 1
      FLASK_RUN_DEBUGGER: 0
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
